backend:
  name: git-gateway
  branch: master
site_url: https://somcareer.com
media_folder: content/assets
public_folder: ../assets

collections:
  - name: jobs
    label: Jobs
    description: somcareer admin panel for posting new jobs.
    folder: content/jobs
    create: true
    delete: true
    slug: "{{title}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "city", label: "City", widget: "string" }
      - { name: "organization", label: "Organization", widget: "string" }
      - {
          label: "posted Date",
          name: "postedAt",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {
          label: "Closing Date",
          name: "closingAt",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { name: image, label: Image, widget: image }
      - {
          name: body,
          label: Body,
          widget: markdown,
          hint: "Main content goes here.",
        }
      - { name: draft, label: Draft, widget: boolean, default: false }
